export { storage, generateId } from './storage';
export { patientService } from './patientService';
export { appointmentService } from './appointmentService';
export { consultationService } from './consultationService';
export { prescriptionService } from './prescriptionService';
export { vitalSignsService } from './vitalSignsService';
export { staffService } from './staffService';
export { barangayStationService } from './barangayStationService';
export { authService } from './authService';
export { dashboardService } from './dashboardService';
